version: '3.8'

# Development override for docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/vendor
    environment:
      - LOG_LEVEL=debug
      - GIN_MODE=debug
    command: ["air", "-c", ".air.toml"]

  mongodb:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # Enable development tools
  mongo-express:
    profiles: []

  redis-commander:
    profiles: []